# Generated by Django 4.1.1 on 2022-09-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('LIBRARIAN', 'LIBRARIAN'), ('MEMBER', 'MEMBER')], default='MEMBER', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookname', models.CharField(max_length=50)),
                ('bookAvailable', models.BooleanField()),
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.books')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.authenticateuser')),
            ],
        ),
    ]
