# Generated by Django 4.1.1 on 2022-09-08 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_books_bookavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookID',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
