# Generated by Django 4.1.1 on 2022-09-08 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_books_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
