# Generated by Django 4.1.1 on 2022-09-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_books_bookpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookPdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='bookpdfs/'),
        ),
    ]
