# Generated by Django 4.1.1 on 2022-09-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_alter_books_bookpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookPdf',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=200),
        ),
    ]
