# Generated by Django 4.1.1 on 2022-09-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_alter_books_bookpdf_alter_books_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookPdf',
            field=models.FileField(max_length=200, null=True, upload_to='media/'),
        ),
    ]
